### PR TITLE
fix: stops custom tooltip from flickering when hovered, fixes #2206

### LINKED ISSUE #2206: Flickering Custom Tooltips
### Describe the bug

With limited space, there are occassions where the tooltip hasn't enough space and renders in a slot where the cursor will manage to hover over the tooltip. When that happens, every move of the mouse causes a flickering re-render of the tooltip

I assume it has something to do with how the mouseover is handled for the tooltips but haven't yet dug deeper

### Reproduction

* Open Slickgrid Universal Example 16
* Open the devtools and reduce the visible area
* hover over the cells of the 3rd column
* 
Image

### Which Framework are you using?

Angular

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| Slickgrid-Universal | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [x] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [x] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by zewa666**
fixes #2206 

This fixes the issue in such a way, that a timeout is added to debounce multiple quick enter/leave event combos. Additionally a 3s total timeout is added to remove the tooltip

https://github.com/user-attachments/assets/f48f62c5-68ac-4660-bc0c-d36d0012bbe3

references https://github.com/ghiscoding/slickgrid-universal/issues/2206

### CODE REVIEW

**Comment by zewa666** [comment]
so this would be a quick shot at fixing the issue but adds a new behavior with the auto-close after 3s (which most likely should be configurable via customTooltip options).

What do you think about this approach?

**Comment by ghiscoding** [comment]
wow this seems like an extreme usage lol... that seems like a lot of code, why not simply not show the tooltip if there's not enough space when doing the positioning of the tooltip? That would be much simpler and you wouldn't have to add listener to all types of mouse events like you just did. 

https://github.com/zewa666/slickgrid-universal/blob/0dd38bdf8a7093558648e503c84fba5d911d4141/packages/custom-tooltip-plugin/src/slickCustomTooltip.ts#L549-L555

**Comment by zewa666** [comment]
the issue happens for us primarily due to grids with more columns than available width. if only a part of the last column is in the visible area, the available space is limited hence the mouseover. not showing the tooltip would feel more like broken UX in said case as a non tech savy user might not get the underlying reason for the missing tooltip

and yep, its quite some code, but essentially all it does is debouncing current events

**Comment by ghiscoding** [comment]
> and yep, its quite some code, but essentially all it does is debouncing current events

but why not use the suggestion I made to do the check in the tooltip reposition function? I think, and would much prefer, less lines of code for what seems like a little check to do before positioning it.

**Comment by zewa666** [comment]
oh ok didnt notice that on phone. will check that out tomorrow 👍

**Comment by ghiscoding** [comment]
hey so I'm not sure if you'll have time to update this PR soon but I'm probably going to go with a release on Monday-Tuesday..ish since I think I'm done with everything including the new Hybrid Selection Model

**Comment by zewa666** [comment]
ok so I tried modifying it as you suggested but that didn't really help. the flickering is back.

```
const gridContainer = this._grid.getContainerNode();
      const gridRect = gridContainer.getBoundingClientRect();
      const cellRect = this._cellNodeElm.getBoundingClientRect();

      
      if (cellRect.right > gridRect.right || cellRect.left < gridRect.left) {
        this._tooltipElm.remove();
        return;
      }
```

I still think the timeout is the solution to all of this, and that unfortunately takes a bit more of code. So while I could squash everything into the reposition method I feel my original approach is cleaner to read.

**Comment by zewa666** [comment]
if you try to replicate the issue as I've shown in the video its pretty obvious. And yes while that example is overkill, the real situation can easily happen with the last column being cut-off by the viewport when there are more columns than width of the grid available

**Comment by ghiscoding** [comment]
that's ok, it was worth the try, I trust you with the best solution. Just make sure to have enough test coverage. Thanks

**Comment by ghiscoding** [comment]
> so this would be a quick shot at fixing the issue but adds a new behavior with the auto-close after 3s (which most likely should be configurable via customTooltip options).
> 
> What do you think about this approach?

and yes this should be a separate option and keep the previous default of always show tooltip

**Comment by zewa666** [comment]
oki doki I think I finally got it, dang need to get prettier sorted on my PC, those linter issues otherwise are a nightmare 🤣

**Review by ghiscoding — CHANGES_REQUESTED** [review]

File: packages/custom-tooltip-plugin/src/slickCustomTooltip.ts [hunk 1]
```diff
@@ -484,6 +518,26 @@ export class SlickCustomTooltip {
     if (finalOutputText.toString()) {
       document.body.appendChild(this._tooltipElm);
 
+      if (this.addonOptions?.persistOnHover === true) {
+        this._tooltipElm.addEventListener('mouseenter', () => {
```
Comment (ghiscoding) [inline packages/custom-tooltip-plugin/src/slickCustomTooltip.ts]: let's use my custom service to bind such events, because with my service we can unbind all easily and avoid any event leaking

for example
```
import { BindingEventService } from '@slickgrid-universal/binding';

protected _bindEventService = new BindingEventService();

init() {
  this._bindEventService.bind(editorResetButtonElm, 'click', (e) => console.log('clicked', e));
}

dispose() {
  this._bindEventService.unbindAll();
}
```

**Comment by zewa666** [comment]
@ghiscoding thx for the review. Some good catches you had there. Sry that it took so long but today was crazy tons of work with all those recent NPM attacks and now the new React one as well.

Btw I took the opportunity to pnpm audit this project and detected a critical for happy-dom, which seems to be caused by vitest. Perhaps updating all packages might be a good idea but I didn't want to do it as part of this PR

**Comment by ghiscoding** [comment]
> @ghiscoding thx for the review. Some good catches you had there. Sry that it took so long but today was crazy tons of work with all those recent NPM attacks and now the new React one as well.
> 
> Btw I took the opportunity to pnpm audit this project and detected a critical for happy-dom, which seems to be caused by vitest. Perhaps updating all packages might be a good idea but I didn't want to do it as part of this PR

no worries, I wasn't aware of the new React attack. For Happy-Dom it comes from Vitest and I removed all usage of Happy-Dom that I had couple of weeks ago and I'm now using JSDOM only (finally). For all deps, I run Renovate on a schedule and I always merge them all before running any new release, there's also Dependabot that runs and identified couple of them recently (I had to add some pnpm overrides for some of them). So I think it's ok on the security audit, I always take care of them as much as possible (not really sure why Happy-Dom shows up though, it should be an optional dep)... I just merged the Renovate PR that was opened, it was including updates to React

**Review by ghiscoding — APPROVED** [review]

**Comment by zewa666** [comment]
ok cool, lemme know if you want anything else sorted otherwise I'll try to fix up the issues caused by the merge this weekend and call it done

**Comment by ghiscoding** [comment]
yeah sorry about that, it looks like I caused the conflict after merging the PR to update dependencies. I just fixed though, so it looks good now. I'll merge after CI run. 

Out of curiosity, are you also planning on fixing the other issue as well? Next week could be fine too, no pressure, just asking ;)

**Comment by zewa666** [comment]
are you talking about the copy/paste issue? could take a look at that one yeah

**Comment by ghiscoding** [comment]
> are you talking about the copy/paste issue? could take a look at that one yeah

yeah the copy selection issue, that's the only other one left :)
